### PR TITLE
Reorganizes architecture diagrams and boms

### PR DESCRIPTION
**Pull request by seansund**
Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

### CODE REVIEW

**Comment by triceam** [comment]
@seansund overall this looks fine.  My only thought: What about our team's boms for creating new dev/test clusters.  Looks liek those are gone.   Do you intend to move those to a different repo, keeping them separate?  Or, should we just add a folder in here?

**Comment by triceam** [comment]
Nevermind, ignore that last comment.  I see them.  I just missed them amongst the other architectures in the `infrastructure` folder.

**Comment by triceam** [comment]
And I assume `ibmcloud-openshift-4-fs` is the current FS cloud reference architecture?

**Comment by triceam** [comment]
Are we still going to use the `solutions` folder and yaml?

**Comment by seansund** [comment]
> Are we still going to use the `solutions` folder and yaml?

I'm thinking we will. We will need to create a similar directory structure in there once we get more content

**Comment by seansund** [comment]
> And I assume `ibmcloud-openshift-4-fs` is the current FS cloud reference architecture?

That was my thinking. We need to capture it somewhere since we will be diverging `3-advanced` from our FS Cloud reference architecture AND continuing to maintain it

**Comment by seansund** [comment]
I made one further change and split the infrastructure into subdirectories by cloud provider

**Pull request merged**
